FROM debian:11

ARG HOME=/root
ARG REPO_BRANCH=actions-debian-container-dev
ARG REPO_URL=https://github.com/romeroalx/pdns.git

# Reusable layer for base update
RUN apt-get update && apt-get -y dist-upgrade && apt-get clean

# Install basic SW and deugging tools
RUN DEBIAN_FRONTEND=noninteractive apt-get -o dir::cache::archives="$APT_CACHE_DIR" -y install \
    sudo git curl gnupg software-properties-common wget \
    ca-certificates apt-utils build-essential vim \
    iproute2 net-tools iputils-* ifupdown cmake acl \
    npm time mariadb-client postgresql-client jq python dnsutils

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# Add LLVM repository
RUN add-apt-repository 'deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-12 main'
RUN wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
RUN apt-get update

# Clone repo an execute basic configuration. Do not delete folder
WORKDIR ${HOME}
RUN git clone ${REPO_URL}

# Install required packages
WORKDIR ${HOME}/pdns
RUN git checkout origin/${REPO_BRANCH}

ARG ASAN_OPTIONS='detect_leaks=0'
ENV ASAN_OPTIONS=${ASAN_OPTIONS}

ARG SANITIZERS=asan+ubsan
ENV SANITIZERS=${SANITIZERS}

ARG FUZZING_TARGETS=yes
ENV FUZZING_TARGETS=${FUZZING_TARGETS}

ARG UBSAN_OPTIONS='print_stacktrace=1:halt_on_error=1:suppressions='${HOME}'/pdns/build-scripts/UBSan.supp'
ENV UBSAN_OPTIONS=${UBSAN_OPTIONS}

ARG UNIT_TESTS=yes
ENV UNIT_TESTS=${UNIT_TESTS}

RUN build-scripts/gh-actions-setup-inv
RUN inv apt-fresh
RUN inv install-clang
RUN inv install-auth-build-deps
RUN inv ci-autoconf
RUN inv ci-auth-configure
RUN inv ci-auth-make
RUN inv ci-auth-install-remotebackend-test-deps
RUN inv ci-make-install

# LMDB backend
# RUN inv install-auth-test-deps -b lmdb

# Copy configuration
# ADD etc/pdns/pdns-lmdb.conf /opt/pdns-auth/etc/pdns-lmdb.conf
# ADD etc/pdns/zones /opt/pdns-auth/etc/zones

# RUN /opt/pdns-auth/sbin/pdns_server --daemon=yes --config-name=lmdb --cache-ttl=0 

# RUN /opt/pdns-auth/bin/pdnsutil --config-name=lmdb load-zone . /opt/pdns-auth/etc/zones/root.zone
# RUN /opt/pdns-auth/bin/pdnsutil --config-name=lmdb load-zone example /opt/pdns-auth/etc/zones/example.zone
# RUN /opt/pdns-auth/bin/pdnsutil --config-name=lmdb list-all-zones

# RUN /opt/pdns-auth/bin/pdns_control --config-name=lmdb quit

EXPOSE 53
CMD ["sleep", "infinity"]
